// <auto-generated />
using System;
using CoreWebApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoreWebApi.Migrations.Entrance
{
    [DbContext(typeof(EntranceContext))]
    [Migration("20190105124735_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreWebApi.Entities.DeletedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Exp");

                    b.Property<string>("Jti")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Jti");

                    b.ToTable("DeletedTokens");
                });

            modelBuilder.Entity("CoreWebApi.Entities.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("Role")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Logins");

                    b.HasData(
                        new { Id = 1, Company = "DefaultCompany", Password = "root", Role = "root", UserName = "root" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
