// <auto-generated />
using System;
using CoreWebApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace CoreWebApi.Migrations
{
    [DbContext(typeof(EntranceContext))]
    partial class EntranceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CoreWebApi.Entities.DeletedToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Exp");

                    b.Property<string>("Jti")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("Jti");

                    b.ToTable("DeletedTokens");
                });

            modelBuilder.Entity("CoreWebApi.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password")
                        .IsRequired();

                    b.Property<string>("UserName")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.ToTable("Users");

                    b.HasData(
                        new { Id = 1, Password = "admin", UserName = "admin" },
                        new { Id = 2, Password = "123", UserName = "张三" },
                        new { Id = 3, Password = "123", UserName = "李四" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
