version: "2"
services:
    mysql:
        image: mysql:5.6
        container_name: server-mysql
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
        labels:
            character-set-server: "utf8mb4"
            collation-server: "utf8mb4_unicode_ci"
        volumes:
            - ./DOCKER_RUNTIME/mysql/data:/var/lib/mysql
        networks:
            - net-mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: server-phpmyadmin
        ports: 
            - "8080:80"
        environment:
            MYSQL_USER: "root"
            MYSQL_PASSWORD: "root"
            MYSQL_ROOT_PASSWORD: "root"
            PMA_HOST: server-mysql
        networks:
            - net-mysql
        
networks:
    net-mysql:
